export interface Country {
  code: string
  name: string
  dial: string
  flag: string
}

export const countries: Country[] = [
  { code: 'CN', name: '中国', dial: '+86', flag: '🇨🇳' },
  { code: 'US', name: 'United States', dial: '+1', flag: '🇺🇸' },
  { code: 'GB', name: 'United Kingdom', dial: '+44', flag: '🇬🇧' },
  { code: 'JP', name: '日本', dial: '+81', flag: '🇯🇵' },
  { code: 'KR', name: '대한민국', dial: '+82', flag: '🇰🇷' },
  { code: 'DE', name: 'Deutschland', dial: '+49', flag: '🇩🇪' },
  { code: 'FR', name: 'France', dial: '+33', flag: '🇫🇷' },
  { code: 'AU', name: 'Australia', dial: '+61', flag: '🇦🇺' },
  { code: 'BR', name: 'Brasil', dial: '+55', flag: '🇧🇷' },
  { code: 'IN', name: 'India', dial: '+91', flag: '🇮🇳' },
  { code: 'CA', name: 'Canada', dial: '+1', flag: '🇨🇦' },
  { code: 'RU', name: 'Россия', dial: '+7', flag: '🇷🇺' },
  { code: 'IT', name: 'Italia', dial: '+39', flag: '🇮🇹' },
  { code: 'ES', name: 'España', dial: '+34', flag: '🇪🇸' },
  { code: 'MX', name: 'México', dial: '+52', flag: '🇲🇽' },
  { code: 'ID', name: 'Indonesia', dial: '+62', flag: '🇮🇩' },
  { code: 'TR', name: 'Türkiye', dial: '+90', flag: '🇹🇷' },
  { code: 'NL', name: 'Nederland', dial: '+31', flag: '🇳🇱' },
  { code: 'SA', name: 'المملكة العربية السعودية', dial: '+966', flag: '🇸🇦' },
  { code: 'CH', name: 'Schweiz', dial: '+41', flag: '🇨🇭' },
  { code: 'SE', name: 'Sverige', dial: '+46', flag: '🇸🇪' },
  { code: 'PL', name: 'Polska', dial: '+48', flag: '🇵🇱' },
  { code: 'BE', name: 'België', dial: '+32', flag: '🇧🇪' },
  { code: 'TH', name: 'ประเทศไทย', dial: '+66', flag: '🇹🇭' },
  { code: 'AR', name: 'Argentina', dial: '+54', flag: '🇦🇷' },
  { code: 'AT', name: 'Österreich', dial: '+43', flag: '🇦🇹' },
  { code: 'NO', name: 'Norge', dial: '+47', flag: '🇳🇴' },
  { code: 'ZA', name: 'South Africa', dial: '+27', flag: '🇿🇦' },
  { code: 'AE', name: 'الإمارات العربية المتحدة', dial: '+971', flag: '🇦🇪' },
  { code: 'DK', name: 'Danmark', dial: '+45', flag: '🇩🇰' },
  { code: 'FI', name: 'Suomi', dial: '+358', flag: '🇫🇮' },
  { code: 'IE', name: 'Ireland', dial: '+353', flag: '🇮🇪' },
  { code: 'PT', name: 'Portugal', dial: '+351', flag: '🇵🇹' },
  { code: 'NZ', name: 'New Zealand', dial: '+64', flag: '🇳🇿' },
  { code: 'GR', name: 'Ελλάδα', dial: '+30', flag: '🇬🇷' },
  { code: 'CZ', name: 'Česká republika', dial: '+420', flag: '🇨🇿' },
  { code: 'RO', name: 'România', dial: '+40', flag: '🇷🇴' },
  { code: 'HU', name: 'Magyarország', dial: '+36', flag: '🇭🇺' },
  { code: 'UA', name: 'Україна', dial: '+380', flag: '🇺🇦' },
  { code: 'CL', name: 'Chile', dial: '+56', flag: '🇨🇱' },
  { code: 'CO', name: 'Colombia', dial: '+57', flag: '🇨🇴' },
  { code: 'PE', name: 'Perú', dial: '+51', flag: '🇵🇪' },
  { code: 'NG', name: 'Nigeria', dial: '+234', flag: '🇳🇬' },
  { code: 'EG', name: 'مصر', dial: '+20', flag: '🇪🇬' },
  { code: 'KE', name: 'Kenya', dial: '+254', flag: '🇰🇪' },
  { code: 'PH', name: 'Philippines', dial: '+63', flag: '🇵🇭' },
  { code: 'VN', name: 'Việt Nam', dial: '+84', flag: '🇻🇳' },
  { code: 'MY', name: 'Malaysia', dial: '+60', flag: '🇲🇾' },
  { code: 'SG', name: 'Singapore', dial: '+65', flag: '🇸🇬' },
  { code: 'HK', name: '香港', dial: '+852', flag: '🇭🇰' },
  { code: 'TW', name: '台灣', dial: '+886', flag: '🇹🇼' },
  { code: 'MO', name: '澳門', dial: '+853', flag: '🇲🇴' },
  { code: 'PK', name: 'Pakistan', dial: '+92', flag: '🇵🇰' },
  { code: 'BD', name: 'Bangladesh', dial: '+880', flag: '🇧🇩' },
  { code: 'IR', name: 'ایران', dial: '+98', flag: '🇮🇷' },
  { code: 'IQ', name: 'العراق', dial: '+964', flag: '🇮🇶' },
  { code: 'IL', name: 'ישראל', dial: '+972', flag: '🇮🇱' },
  { code: 'MA', name: 'المغرب', dial: '+212', flag: '🇲🇦' },
  { code: 'DZ', name: 'الجزائر', dial: '+213', flag: '🇩🇿' },
  { code: 'TN', name: 'تونس', dial: '+216', flag: '🇹🇳' },
  { code: 'KZ', name: 'Қазақстан', dial: '+7', flag: '🇰🇿' },
]
